export const nonDisclosureAgreement = {
    title: 'NON-DISCLOSURE AGREEMENT',
    subTitle: 'Please Read carefully',
    body: 'In connection with the consideration of a possible negotiated transaction between you and all entities whose information is available on FNEX and/or one or more of its subsidiaries, affiliates or divisions, (collectively the “Parties"), the Parties hereto contemplate the transfer of certain confidential information. This Agreement is mutually binding upon the Parties as to each provision. Hereinafter, for purposes of this Agreement the term “Company” shall refer to the party furnishing certain confidential information and “you” shall refer to the party that received or will receive from the Company certain confidential information.\n' +
        'As a condition of being furnished that information, you shall treat any and all information concerning the Company (whether prepared by the Company, its advisors or otherwise, and whether written or oral) which has been or will be furnished to you by or on behalf of the Company or any affiliate thereof whether in writing or oral, or whether received directly or indirectly, (collectively "Confidential Information") in accordance with the provisions of this confidentiality agreement and shall take or abstain from taking certain other actions herein set forth. The term "Confidential Information" does not include information which (i) is already in your possession (other than information previously furnished to you by the Company or any affiliate thereof), provided that such information is not known by you to be subject to another confidentiality agreement with or other obligation of secrecy to the Company, or (ii) becomes generally available to the public other than as a result of a disclosure by you or your directors, officers, employees, agents or advisors, representatives, lenders and others associated with you (collectively "Representatives"), or (iii) becomes available to you on a non-confidential basis from a source other than the Company or its advisors, provided that such source is not known by you to be bound by a confidentiality agreement with or other obligation of secrecy to the Company, or (iv) is independently developed by you. Confidential Information shall not be deemed to be generally available to the public or in the public domain merely because any part of any Confidential Information is embodied in general disclosures or because individual features, components, or combinations thereof are now known or become known to the public.\n' +
        'Without limitation, the term "Confidential Information" includes (i) financial statements, financial data and financial information regarding the Company, its financial conditions and the results of its operations, (ii) Company’s materials, reports, plans, analyses, financial projections, documents, drawings, machines, writings, samples, studies, compilations, tools, models, devices, business plans, strategies, customer information, marketing and proposal information, financial and rate information, personal information, and the terms and provisions of the Company\'s leases, (iii) the tax returns of the Company, and (iv) all analyses, compilations, excerpts, forecasts, summaries, studies, or other documents prepared by you or your Representatives which contain or relate to information about the Company and/or your interest in the Company.\n' +
        '\n' +
        'You hereby confirm that you are aware that the Confidential Information is confidential and you shall respect its confidential nature, hold the Confidential Information in trust, and take normal and reasonable precautions to maintain such confidentiality so that none of the Confidential Information, except as otherwise provided herein, will be divulged to any other party.\n' +
        'You hereby agree that the Confidential Information shall be used solely for the purpose of evaluating a possible negotiated transaction with the Company and not used in any manner detrimental to Company and that such information will be kept confidential by you; provided, however, that (i) any of such information may be disclosed to your directors, officers and employees to the extent they need to know such information for the purpose of evaluating the proposed transaction (it being understood that such directors, officers and employees shall be informed by you of the confidential nature of such information and shall be directed by you to treat such information confidentially in accordance with the terms of this confidentiality agreement) and you shall require them to agree to act in accordance with the terms and conditions of this agreement, and (ii) any other disclosure of such information may be made to which the Company consents in writing. Upon request by Company, you agree you will advise Company in writing within a reasonable time of all persons who have been given access to or knowledge of Confidential Information of any kind. You agree you will not disclose the existence of your discussions with Company of a possible negotiated transaction without Company’s express written consent to such disclosure. You agree you will not discuss with or offer to any third party a participation in the possible negotiated transaction. You agree you will not directly or indirectly contact or communicate with any executive or employee of Company, any customer of Company, or any vendor of Company, without in each such instance the express\n' +
        'advance written consent of Company, which Company may grant or withhold in its sole discretion. You agree you will not hire or solicit for employment any key employee of Company for a period of one (1) year.\n' +
        'You hereby acknowledge that you are aware, and that you will advise such directors, officers and employees who are informed as to the matters which are the subject of this confidentiality agreement, that the United States securities laws and regulations prohibit any person who has received from an issuer material, non-public information concerning such issuer from purchasing or selling securities of such issuer or from communicating such information to any other person under circumstances in which it is reasonably foreseeable that such person is likely to purchase or sell such securities.\n' +
        'If you receive a request to disclose or are required to disclose all or any part of the information contained in the Confidential Information (by oral questions, interrogatories, requests for information or other documentary subpoena, civil investigative demand or other processes), you shall, to the extent permitted by law (i) immediately notify the Company of the existence, terms and circumstances surrounding such a request or requirement, (ii) consult with the Company on the advisability of taking legally available steps to resist or narrow such request, and if requested by Company, resist such disclosure or portions thereof at Company\'s expense and under Company\'s direction, and (iii) if disclosure of such information is required, exercise your best efforts to obtain an order or other reliable assurance that confidential treatment will be accorded to such portion of the disclosed information which the Company so designates.\n' +
        'You understand that neither the Company nor any of its directors, officers, employees, representatives or advisors has made or makes any representation or warranty as to the accuracy or completeness of the Confidential Information, however, Company will use reasonable efforts to provide accurate and complete Confidential Information. You agree that neither the Company nor any of its directors, officers, employees, representatives, or advisors shall have any liability to you or any of your representatives or advisors resulting from the use of the Confidential Information.\n' +
        'Without Company\'s prior written consent, you will not and you will direct your Representatives not to disclose to any person, including without limitation any employee, customer, landlord, potential customer or other person having business dealings with Company of either the fact that any investigations, discussions, or negotiations are or may take place concerning a possible transaction between you and Company or that you have requested or received Confidential Information from Company or any of the terms, conditions or other facts with respect to any possible transaction, including the status thereof. The term "person" as used in this agreement shall be interpreted broadly to include, without limitation, any corporation, company, partnership, limited liability company, individual or other entity. It is agreed that (i) all communications regarding a possible transaction, (ii) all requests for additional information regarding Company, (iii) all requests for facility tours and (iv) all discussions or questions regarding Company or procedures will be submitted or directed in a confidential fashion to the Company’s Chief Executive Officer.\n' +
        'If you elect not to submit or enter into a negotiated transaction with Company, Company elects not to submit or enter into a negotiated transaction with you, or otherwise, upon request to Company, you shall promptly redeliver to Company all written Confidential Information (whether prepared by Company, its advisors, or otherwise) and you will not retain any copies, extracts or other reproductions in whole or in part of such written materials. Also, all documents, memoranda, notes and other writings whatsoever prepared by you or your advisors based on the information in the Confidential Information shall be destroyed, and such destruction shall be certified in writing to Company by an authorized officer supervising such destruction.\n' +
        '\n' +
        'Company may terminate access to you and your Representatives to the Confidential Information at any time. Company has no duty or obligation to provide information, whether Confidential Information or otherwise, to you. Company has no duty to negotiate with you, may terminate negotiations with you at any time, and may negotiate with others. This agreement contains the entire understanding between the parties with respect to the matters contemplated by this agreement and supersedes all prior written or oral communications, negotiations, understandings or agreement of any kind with respect to such matters. No amendment or modification of this agreement shall be effective unless made or agreed to in writing. This agreement shall be binding upon the parties and the Representatives and their respective successors and assigns and shall inure to the benefit of the parties and their respective successors and assigns. The person executing this confidentiality agreement on your behalf hereby represents and warrants that they are authorized and duly empowered to execute this confidentiality agreement and bind you. If any provision set forth in this agreement relative to your being furnished with Confidential Information is deemed not enforceable in whole or in part, the remaining provisions set forth in this agreement shall be enforceable notwithstanding the validity or invalidity of any other provisions. Any provision not enforceable in part shall be enforced to the extent valid and enforceable. No failure or delay by Company in exercising any right, power or privilege under this agreement shall operate as a waiver thereof, nor shall any single or partial exercise thereof preclude any other or further exercise of any right, power or privilege under this agreement.\n' +
        'You agree that Company shall be entitled to equitable relief, including injunction and specific performance, in the event of any breach of the provisions of this confidentiality agreement, in addition to all other remedies available to Company at law or in equity. You also agree that you will pay all costs and reasonable attorneys\' fees incurred by Company in the event of your breach or threatened breach of this confidentiality agreement.\n' +
        'Your obligations under this confidentiality agreement shall be governed by, and construed in accordance with, the laws of the State of Indiana applicable to contracts made and to be wholly performed in Indiana. This confidentiality agreement and Your obligations hereunder shall terminate two years after the date hereof.\n' +
        '\n'
}

export const termsOfUse = {
    title: 'Terms of Use',
    subTitle: 'Please Read carefully',
    body: `1. Terms of Use<br/>` +
        '\n' +
        'a. Summary- These Terms of Use ("Agreement") should be read carefully before using the services offered by FNEX, LLC and those of its subsidiaries and affiliates, including APPLIED CAPITAL, LLC (collectively referred to as “FNEX”), or accessing the websites of FNEX or those of its subsidiaries and affiliates. This Agreement sets forth the legally binding terms and conditions for your use of the website at www.fnex.com (the "Site") and the services owned and operated by FNEX (the "Service"). Usage of the Site or Service in any manner constitutes acceptance of this Agreement and any other rules, policies or procedure present on the site. This Agreement and additional rules, policies and procedures will be updated. These updates are hereby incorporated by reference. Use of this site is governed by the most recently published Agreement and applicable rules, policies and procedures. No notice will be provided upon publishing of an updated Agreement. This Agreement applies to all users of the Site and Service. If you do not agree to all the terms of this Agreement and/or FNEX’s Privacy Policy, you are not eligible to participate in FNEX’s Service or otherwise use this Site.\n' +
        '\n' +
        'b. Investor Qualifications- Offerings on the Site are available only to Accredited Investors. FNEX follows the definition of Accredited Investor found in SEC Regulation Rule D. Some offerings may not be available to all Accredited Investors. By using this Site, you certify that you are an Accredited Investor or an advisor to Accredited Investors. By using this Site, you verify that you are legally capable of forming a binding contract and that all the information you submit is accurate and truthful. By completing an investment you certify that you are qualified for that investment and the investment is suitable considering your financial needs and investment criteria. You hereby acknowledge that Applied Capital, LLC may receive a fee from the Issuer or Selling Parties for any offering you access through the platform. If you are using the Site on behalf of any such entity, you represent and warrant that you are authorized to accept this Agreement on the entity’s behalf, and that such entity agrees to indemnify FNEX for violations of this Agreement. FNEX reserves the right to suspend or discontinue your access to the Site or Service at any time. FNEX further reserves the right, in its sole discretion, to block or otherwise discontinue your access and use of the Site at any time and for any reason. You agree that FNEX and its subsidiaries and affiliates will not be liable to you or to any third party for any such modification, suspension or discontinuance.\n' +
        '\n' +
        'c. Securities Products- Offerings on this Site are only suitable for prospective investors who are familiar with, fully comprehend and are willing to accept high risk. Securities sold through private placements are not publicly traded and, therefore, are less liquid. Additionally, Investors may receive restricted stock that may be subject to holding period requirements and other restrictions on resale. Companies seeking private placement investments tend to be in earlier stages of development and thus have not yet been fully tested in the public marketplace. Investing in such private placements requires high risk tolerance, low liquidity concerns, and long-term commitments. For those reasons, Investors must be able to afford to lose their entire investment. The value of investments and the income from them can fall as well as rise. Past performance is not a guarantee of future performance. The contents of this Site do not constitute financial, legal or tax advice. Investors are solely responsible for conducting any legal, accounting or due diligence review. You should obtain investment and tax advice from your advisers before deciding to invest. Investment products are not FDIC insured, may lose value, and there is no bank guarantee. None of the information contained in the publicly available portions of the Site constitutes a recommendation, solicitation or offer to buy or sell any securities, options or other financial instruments or other assets or provide any investment advice or service. The information contained in the Site has been prepared without reference to any particular User\'s investment requirements or financial situation. The information and services provided on the Site are not provided to, and may not be used by, any person or entity in any jurisdiction where the provision or use thereof would be contrary to applicable laws, rules or regulations of any governmental authority or where FNEX is not authorized to provide such information or services. Some products and services described in the Site may not be available in all jurisdictions or to all clients.\n' +
        '\n' +
        'd. Underwriting- FNEX is not an underwriter of any securities offered on the Site, unless specifically noted. FNEX is authorized to take customer orders for the purchase of the securities on the Site. FNEX has not taken any steps to verify the adequacy, accuracy or completeness of any information.\n' +
        '\n' +
        'e. Modification of Agreement- FNEX reserves the right, at its sole discretion, to modify or replace any of the terms of this Agreement, or change, suspend or discontinue the Service (including without limitation, the availability of any feature, database or content) at any time. Such modifications shall become part of this Agreement and are automatically effective once posted on the Site. This Agreement may not be orally amended. FNEX may also impose limits on certain features and services or restrict your access to parts or all of the Service without notice or liability. It is your responsibility to check the terms of this Agreement periodically for changes. Your continued use of the Service following the posting of any changes to the Terms of Use constitutes acceptance of those changes.\n' +
        '\n' +
        'f. Proprietary Rights- The FNEX logo is a trademark and service mark of FNEX. FNEX or its licensors own and retain all proprietary rights in the Site, the Service and all material and information posted thereon ("Content"). The Site contains the copyrighted material, trademarks and other proprietary information of FNEX and its licensors. You may not alter, modify, publish, distribute, publicly display or sell any Content or other such proprietary information, or otherwise copy or transmit any Content or other such proprietary information without the express written permission of FNEX. In addition, to the extent you receive information from FNEX, Issuers or other Investors with respect to any Investment activity on the Site, you may not further disclose or otherwise provide such information to another party in any way that allows a personal identification of such Issuer or Investor. You agree that FNEX may, at its sole discretion and to the extent permitted by law, access, read, preserve and disclose your account information, usage history and submitted Content in order to: (a) comply with any applicable law, regulation, legal process, or governmental request; (b) respond to claims that any Content violates the rights of third parties, including intellectual property rights; (c) enforce this Agreement and investigate potential violations thereof; (d) detect, prevent, or otherwise address fraud, security, or technical issues; (e) respond to your requests for customer service; or (f) protect the rights, property, or personal safety of FNEX, its users, or the public.\n' +
        '\n' +
        'g. Authorized User- Our Services and certain pages of the Site are available only to Investors who have been authorized by us to access those Services and web pages on the Site. Such authorization may require completion of an investor questionnaire and satisfactory background information screening and/or identification verification. Only users of FNEX with a valid User ID and password are authorized to access such services and web pages. Unauthorized use of the Site and our Service, including, but not limited to the misuse or sharing of passwords or misuse of any other information, is strictly prohibited. You may not use the Site in any manner that could damage, disable, overburden or impair the Site or Service or interfere with any other party\'s use and enjoyment of the Site or Service. You agree that you will not engage in any activities related to the Site that are contrary to applicable laws or regulations. You further agree that you are responsible for any unauthorized use of your password that is made before you have notified us and we have had a reasonable opportunity to act on that notice. FNEX reserves the right at its discretion to suspend or cancel your password, even without receiving such notice from you, if we suspect that it is being used in an unauthorized or fraudulent manner. Notwithstanding the above, you are responsible for monitoring your account and should promptly report any unauthorized or suspicious activity in your account to us at info@FNEX.com.\n' +
        '\n' +
        'h. Use of Links- The Site may permit you to link to other websites or resources on the Internet, and other websites or resources may contain links to the Site. When you access third party websites, you do so at your own risk. These other websites are not under FNEX\'s control, and you acknowledge that FNEX is not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. Nor does FNEX endorse, investigate or adopt any third party content and makes no representations or warranties of any kind regarding such content. You further acknowledge and agree that FNEX shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any information, goods or services available on or through any such website or resource. You should also be aware that the terms and conditions and privacy policy of such sites may be different from those applicable to your use of the FNEX Site and Service.\n' +
        '\n' +
        'i. Third Party Content- Certain portions of the Site may contain third party content and may provide links to webpages and content of third parties (collectively "Third Party Content"). FNEX makes no representations or warranties of any kind regarding the Third Party Content, including with respect to its accuracy or completeness. You acknowledge and agree that FNEX is not responsible or liable in any manner for any Third Party Content or your reliance upon Third Party Content. Users use such Third Party Content at their own risk.\n' +
        '\n' +
        'j. Termination- FNEX may terminate your access to all or any part of the Site and Service at any time, with or without cause, with or without notice, effective immediately, which may result in the forfeiture and destruction of all information associated with your membership. All provisions of this Agreement shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. Further, you agree that FNEX and its subsidiaries and affiliates will not be liable to you or to any third party for any such termination, suspension or discontinuance.\n' +
        '\n' +
        'k. Warranty Disclaimer- FNEX has no special relationship with or fiduciary duty to you. You acknowledge that FNEX has no control over, and no duty to take any action regarding: which users gains access to the Site; what Content you access via the Site; what effects the Content may have on you; how you may interpret or use the Content; or what actions you may take as a result of having been exposed to the Content. You release FNEX from all liability for you having acquired or not acquired Content through the Site. FNEX makes no representations concerning any Content contained in or accessed through the Site, and FNEX will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Site or the Service.\n' +
        '\n' +
        'l. Representations & Warranties- FNEX neither represents, warrants, nor promises any specific results from use of the Site. THE SITE, INCLUDING ANY CONTENT OR INFORMATION CONTAINED WITHIN IT OR ANY SERVICE OR ADVICE PROVIDED IN CONNECTION WITH THE SERVICE, IS PROVIDED "AS IS" WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS SITE AND SITE-RELATED SERVICES. FNEX makes no representation or warranty, express or implied, with respect to any third party data provided to FNEX or its transmission, timeliness, accuracy or completeness, including but not limited to implied warranties or warranties of merchantability or fitness for a particular purpose. FNEX will not be liable in any way to you or to any other person for any inaccuracy, error or delay in or omission of any third party data or the transmission or delivery of any such third party data and any loss or damage arising from (a) any such inaccuracy, error, delay or omission, (b) non-performance or (c) interruption in any such third party data due either to any negligent act or omission by FNEX or "force majeure" or any other cause beyond the control of FNEX. THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" AND IS WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. YOUR USE OF THE SERVICE IS SOLELY AT YOUR OWN RISK.\n' +
        '\n' +
        'm. Electronic Communication Privacy Act Notice (18usc 2701-2711): FNEX makes no guarantee of confidentiality or privacy of any communication or information transmitted on the site or any website linked to the site. FNEX will not be liable for the privacy of email addresses, registration and identification information, disk space, communications, confidential or trade-secret information, or any other Content stored on FNEX\'s equipment, transmitted over networks accessed by the Site, or otherwise connected with your use of the Service.\n' +
        '\n' +
        'n. Indemnification- You shall defend, indemnify, and hold harmless FNEX, its affiliates and each of its employees, contractors, directors, suppliers and representatives from all liabilities, claims, and expenses, including reasonable attorneys\' fees, that arise from or relate to your use or misuse of, or access to, the Site, Service, Content or otherwise from your User Submissions, violation of the Agreement, or infringement by you, or any third party using your account, of any intellectual property or other right of any person or entity. FNEX reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with FNEX in asserting any available defenses.\n' +
        '\n' +
        'o. Limitation of Liability- IN NO EVENT SHALL FNEX, NOR ITS DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS OR CONTENT PROVIDERS, BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICE (I) FOR ANY LOST PROFITS, DATA LOSS, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, SUBSTITUTE GOODS OR SERVICES (HOWEVER ARISING), (II) FOR ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE (REGARDLESS OF ORIGINATION), OR (III) FOR ANY DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) ONE-HUNDRED U.S. DOLLARS ($100.00). THE EXCLUSION OR LIMITATION ON DAMAGES IS VOID WHERE PROHIBITED.\n' +
        '\n' +
        'p. Non-compete- You agree not to contact any individual entity listed on FNEX with any business proposal with may be in direct or indirect competition with FNEX and/or its respective partners and/or affiliate organizations. You further agree that you will not contact any company, issuer, investment bank, fund or other product sponsor listed on the FNEX platform without the written approval from FNEX, nor will you attempt to circumvent any relationship between any product sponsor and FNEX, or attempt to contact any such sponsor for purposes of securing an offering by such sponsor on a competitive platform. You agree that any violation of this section shall entitle FNEX to any lost revenue associated such violation plus treble damages.\n' +
        '\n' +
        'q. Governing Law- This Agreement (and any further rules, policies or guidelines incorporated by reference herein) shall be governed by and construed in accordance with the laws of the State of Indiana, without giving effect to any principles of conflicts of law. (Arbitration).\n' +
        '\n' +
        'r. Venue- If a party commences an action related to FNEX, the action shall be commenced in Marion County, Indiana, and each party hereto waives his or her right to file a Forums Non Conveniens action, and submits to jurisdiction in Indiana. FNEX uses waive the right to seek class action certification for claims related to FNEX services and the services of entities using FNEX services.\n' +
        '\n' +
        's. Registration Data; Account Security- In consideration of your use of the Site, you agree to (a) provide accurate, current and complete information about you as may be prompted by any registration forms on the Site ("Registration Data"); (b) maintain the security of your password and identification; (c) maintain and promptly update the registration Data, and any other information that you provide to FNEX, to keep it accurate, current and complete; and (d) accept all risks of unauthorized access to the Registration Data and any other information you provide to FNEX.\n' +
        '\n' +
        't. Integration and Severability- This Agreement is the entire agreement between you and FNEX with respect to the Service and use of the Site, and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and FNEX with respect to the Site. If any provision of the Terms of Use is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Agreement will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.\n' +
        '\n' +
        'u. Managed Futures- All Managed Futures, including commodities, are offered by Capital Trading Group, registered with the Commodity Futures Trading Commission ("CFTC") as an introducing broker and member of the National Futures Association ("NFA"). By accessing this site and any pages thereof, you agree to be bound by its Terms of Use. FNEX does not make any recommendations regarding the appropriateness of particular opportunities for any Investor. Investors must conduct their own investigation of the merits and risks of each opportunity. Use of this website does not constitute an offer by FNEX to sell, solicit or make an offer to buy any such investment interest in any business venture. FNEX Users are subject a "cooling down" period after becoming a member and participating in any offering on the website. FNEX does not give or offer any business advice, investment advice, tax advice or legal advice to anyone using the website or the Services as defined herein the Terms of Use. For information regarding FINRA or individual brokers, go to www.finra.org or call the BrokerCheck hotline at (800) 289-9999. Information regarding BrokerCheck is available upon request.\n' +
        'Referral Fee Terms\n' +
        'These Referral Fee Terms constitute a legal agreement between you, as the user of the FNEX.com Website, and FNEX, LLC, as the owner of the Website. Throughout these Referral Fee Terms we will refer to you as "you", and we will refer to FNEX, LLC as "we", "us" or "FNEX".\n' +
        '1. Application\n' +
        'These Referral Fee Terms set out the terms on which we intend to pay you fees for referring new users to FNEX. They apply to you as soon as you first use the Website, and you are deemed to have agreed to be bound by them upon your first use of the Website. If you do not wish to continue to be bound by these Referral Fee Terms, please stop using the Website now.\n' +
        '2. Relationship to Other Agreements\n' +
        'In addition to these Referral Fee Terms, our Confidentiality terms and Terms of Use apply to you and everyone else who uses the Website. A Privacy notice also sets out details of how your personal data will be used. Together, these are the "Website Agreements".\n' +
        'During the course of your use of the Website, you are bound by these Website Agreements. If you wish to join FNEX as a member, you will need to agree to the Website Agreements which set out the substantive terms that govern your relationship with us when you make use of our Website.\n' +
        'With respect to our Referral Fees:\n' +
        'You cannot refer yourself;\n' +
        'You cannot refer a person that is an existing or past member or client with FNEX or FNEX Capital in any capacity;\n' +
        'FNEX reserves the right in its sole and absolute discretion to decline services to a referred party at any time;\n' +
        'FNEX may discontinue its Referral Program at any time and will not be liable for any loss of income or further referral fees;\n' +
        'FNEX may decline a referral at any time without giving a reason;\n' +
        'In the event of conflicting referrals, FNEX reserves the right to determine who receives the credit for such referrals;\n' +
        'You are not permitted, under any circumstances, to represent that you are acting on behalf of FNEX or that you have the authority to enter in any agreement on behalf of FNEX;\n' +
        'Referral fees will be paid, based upon these terms, quarterly; and\n' +
        'Referral Fees are ONLY paid upon the first investment by a referred party. Subsequent investments by a referred party are not eligible for a Referral Fee.\n' +
        '3. Structure of Referral Fees\n' +
        'From time to time, we may have in place arrangements by which we pay you referral fees for referring investors or businesses to FNEX.\n' +
        'Currently, we have one type of referral fee arrangement in place:\n' +
        '$1000 Referral Fee: this referral fee is paid to you when you, as a FNEX member, (a) refer a new investor to www.FNEX.com with a link provided on the Website, AND (b) the new investor uses this referral link to sign up for the FNEX.com platform AND (c) that new investor makes an investment with FNEX. Upon the occurrence of all three of these actions a Referral Fee will be paid directly to you by check. Referral Fees are ONLY paid on the first investment by a referred party. Subsequent investments by a referred party are not eligible for a Referral Fee.\n' +
        'Our Referral Fees are subject to change or be withdrawn at any time and entirely at our discretion. Such changes may impact the fees payable in respect of referrals you have already made. Any new referral fee system will be described on one or more pages of the Website or in another form of notice to you. All referral fees will be paid gross of any tax you may be required to pay.\n' +
        '4. Identification and Regulatory Requirements\n' +
        'We will generally pay your referral fees to you at the time the relevant investment transaction is completed. However, we may require you to pass anti-money laundering checks or other identification checks, or to satisfy other regulatory requirements, and we may decline to pay you any referral fees until and unless you have done so. If you do not pass such checks or satisfy such requirements within a reasonable period of time, we may cancel your referral fees.\n' +
        '5. Exceptions\n' +
        'Our referral fee system is intended to encourage you to refer genuinely new investors to FNEX. We therefore reserve the right to refuse to pay referral fees in respect of an individual or business that is directly connected with you. That may include an immediate family member or a company which you control, but it may also include other relationships where we believe that payment of referral fees would not be consistent with the purpose of this system. The determination as to whether to refuse to pay referral fees will be made entirely at our discretion.\n' +
        '6. Severability\n' +
        'However, in the event that any of these provisions are found to be unlawful, invalid or otherwise unenforceable, that provision is to be deemed severed from these Referral Fee Terms and shall not affect the validity and enforceability of the remaining Referral Fee Terms. This clause on "Severability" shall apply only within jurisdictions where a particular term is illegal.\n' +
        '7. No Waiver\n' +
        'In the event that either you or we fail to exercise any right or remedy contained in these Referral Fee Terms, that does not mean you or we (as applicable) have waived that right or remedy and so shall not be construed as a waiver.\n' +
        '8. Revisions\n' +
        'From time to time we may update these Referral Fee Terms to take account of changes in the law or for any other reason. If we update these Referral Fee Terms, we will post a new version on the Website, and as soon as you use the Website after they are posted, you will be deemed to have agreed to the updated version, but you will still be bound by the terms of any previous versions to which you have agreed or been deemed to agree. If there is a conflict between two versions of the Referral Fee Terms to which you have agreed or been deemed to agree, the more recent version shall take precedence unless it is expressly stated otherwise.\n' +
        '9. Communications\n' +
        'If you wish to communicate with us about anything related to these Referral Fee Terms, you may do so by sending an email to info@FNEX.com.\n' +
        '10. Choice of Law\n' +
        'These Referral Fee Terms shall be governed by and construed in accordance with the laws of Indiana.\n' +
        '11. Jurisdiction\n' +
        'You agree to submit to the exclusive jurisdiction of the courts Marion County, Indiana. This means that if you want to bring a legal action against us, or we want to bring a legal action against you, it must be done in one of these courts.\n' +
        '12. Definitions\n' +
        'We have used a few capitalized terms in this agreement, which means that they have specific definitions. In some cases the definition is set out when they are first used, but in a few cases we give the meaning below instead.\n' +
        'Privacy Policy means the privacy notice of the Website, available at Privacy notice;\n' +
        'Terms of Use means the Terms of Use of the Website, available at Terms of Use; and\n' +
        'Website means the website that you are currently using (www.FNEX.com) and any sub-domains of this site unless expressly excluded by their own terms and conditions.\n' +
        '\n' +
        '\n'
}
